keypress_delay_ms: 20

modmap:
  - name: Global
    remap:
      Space:
        held: KEY_LEFTSHIFT
        alone: Space
        alone_timeout_millis: 200
  # - name: TerminalCapsLock
  #   remap:
  #     KEY_CAPSLOCK:
  #       held: KEY_LEFTCTRL
  #       alone: KEY_ESC
  #       alone_timeout_millis: 300
  #   application:
  #     only: com.mitchellh.ghostty
  - name: CapsLock
    remap:
      KEY_CAPSLOCK:
        held: KEY_CAPSLOCK
        alone: KEY_ESC
        alone_timeout_millis: 300
  - name: IME and KeySwap
    remap:
      KEY_LEFTMETA:
        held: KEY_LEFTCTRL
        alone: KEY_HANJA
        alone_timeout_millis: 300
      KEY_RIGHTMETA:
        held: KEY_RIGHTCTRL
        alone: KEY_HANGEUL
        alone_timeout_millis: 300
      KEY_LEFTCTRL: KEY_LEFTMETA
      KEY_RIGHTCTRL: KEY_RIGHTMETA

virtual_modifiers:
  - CapsLock
keymap:
  - name: Emacs Like Cursor Move
    remap:
      CapsLock-f: Left
      CapsLock-b: Right
      CapsLock-p: Up
      CapsLock-n: Down
      CapsLock-a: Home
      CapsLock-e: End
      # 残りはCapsLockをCtrlの操作に変換する
      CapsLock-d: Ctrl-d
      CapsLock-h: Ctrl-h
      CapsLock-u: Ctrl-u
      CapsLock-k: Ctrl-k
      CapsLock-y: Ctrl-y
      CapsLock-w: Ctrl-w
      CapsLock-t: Ctrl-t
      CapsLock-g: Ctrl-g
      CapsLock-r: Ctrl-r
      CapsLock-j: Ctrl-j
      CapsLock-x: Ctrl-x
      CapsLock-c: Ctrl-c
      CapsLock-q: Ctrl-q
      CapsLock-s: Ctrl-s
      CapsLock-o: Ctrl-o
      CapsLock-KEY_SEMICOLON: KEY_BACKSPACE
      CapsLock-Shift-KEY_SEMICOLON: KEY_DELETE

  - name: 1password extension
    remap:
      CapsLock-Shift-x: M-Shift-x
  - name: deepl extension
    remap:
      CapsLock-Shift-y: M-Shift-y
  - name: raindrop
    remap:
      CapsLock-Shift-s: M-Shift-s
  - name: mouse dictionay
    remap:
      CapsLock-Shift-y: M-Shift-d
  - name: ScreenLock
    remap:
      CapsLock-Ctrl-q: Ctrl-Super-q
  - name: Clipboard Paste
    remap:
      CapsLock-Ctrl-v: Ctrl-Super-v

shared:
  terminals: &terminals
    - com.mitchellh.ghostty
