[settings]
experimental = true

[tools]
deno = "latest"
node = "latest"
python = "system"
"pipx:terminaltexteffects" = "latest"
go = "latest"
ghq = "latest"
bat = "latest"
ripgrep = "latest"
zoxide = "latest"
fzf = "latest"
fd = "latest"
starship = "latest"
zellij = "latest"
delta = "latest"
lazygit = "latest"
"go:github.com/go-task/task/v3/cmd/task" = "latest"
"ubi:tstack/lnav" = "latest"
bottom = "latest"
"npm:czg" = "latest"
glow = "latest"
uv = "latest"
"npm:@devcontainers/cli" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:ccusage" = "latest"
"npm:difit" = "latest"
pnpm = "latest"
rust = "latest"
"cargo:diff-tui" = "latest"
bun = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
